### ISSUE TITLE
Support for docinfo.xml definitions

### ISSUE THREAD

**Issue by butcherpete** [asciidoctor/asciidoctor-docbook.js#16]
I have been unable to ingest docinfo file information (https://asciidoctor.org/docs/user-manual/#docinfo-file) and add metadata to XML output. Works fine using asciidoctor command line: https://asciidoctor.org/man/asciidoctor/

I generate XML output just fine, but the metadata specified the docinfo is not produced.   The metadata specified in the ADOC file itself is presented.

Added `:docinfo: shared` to ADOC file.  Added docinfo.xml file to same directory. Expected the content to be added:

````xml
<author>
  <personname>
    <firstname>Karma</firstname>
    <surname>Chameleon</surname>
  </personname>
  <affiliation>
    <jobtitle>Word SWAT Team Leader</jobtitle>
  </affiliation>
</author>

<keywordset>
  <keyword>open source</keyword>
  <keyword>documentation</keyword>
  <keyword>adventure</keyword>
</keywordset>

<printhistory>
  <para>April, 2019. Twenty-sixth printing.</para>
</printhistory>
````

LIke I said, the asciidoctor command works using the same ADOC and DOCINFO.XML

**Comment by Mogztter** [comment]
Hello @butcherpete 

Could you please share the exact command you are running?
Also could you please run:

```
$ asciidoctor --version
```

Thanks!

**Comment by Mogztter** [comment]
I've added a test case, it seems to be working: https://github.com/asciidoctor/asciidoctor-docbook.js/pull/18

**Comment by butcherpete** [comment]
````
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
````
This works:
````
$ asciidoctor -b docbook5 -d article -D output input/quickstart.adoc
````

This doesn't
````
'use strict';

const fs = require('fs')
const asciidoctor = require('@asciidoctor/core')()
require('@asciidoctor/docbook-converter')()

const options = {
	attributes: { backend: 'docbook5', doctype: 'book'},
  standalone: true
}

const content = require('fs').readFileSync('./input/asciidoc-writers-guide.adoc');

const docbook = asciidoctor.convert(content, options);

//console.log(docbook);

fs.writeFile('./output/asciidoc-writers-guide2.xml', docbook, err => {
  if (err) {
    console.error(err)
    return
  }
  //file written successfully
})

````

**Comment by Mogztter** [comment]
Oh I see. That's because you are using `convert` with the content of the file. In this case, Asciidoctor does not know about the location of your file since your input is just a string.

You should use `convertFile`:

```js
'use strict';

const asciidoctor = require('@asciidoctor/core')()
require('@asciidoctor/docbook-converter')()

const options = {
  backend: 'docbook5',
  doctype: 'book',
  standalone: true,
  to_file: './output/asciidoc-writers-guide2.xml'
}

asciidoctor.convertFile('./input/asciidoc-writers-guide.adoc', options);
```

Please note that I didn't run the above code but I'm sure you get the idea.
Alternatively, your can use the Asciidoctor.js CLI which is (mostly) compatible with the Asciidoctor (Ruby) CLI.

**Comment by butcherpete** [comment]
I tried using your code and I still do not see the content of the :docinfo: file in the generated XML.

I don't know if this is relevant, but I attempted to switch over from the ruby CLI to the JS CLI, and I am now getting errors about  a `missing converter for backend 'docbook5'`.

**Comment by Mogztter** [comment]
> I tried using your code and I still do not see the content of the :docinfo: file in the generated XML.

Ooops I think you also need to set safe mode to 'safe'.

```js
const options = {
  backend: 'docbook5',
  doctype: 'book',
  standalone: true,
  safe: 'safe',
  to_file: './output/asciidoc-writers-guide2.xml'
}
```

> I don't know if this is relevant, but I attempted to switch over from the ruby CLI to the JS CLI, and I am now getting errors about a missing converter for backend 'docbook5'.

I don't think it's related, did you require the docbook converter? In Asciidoctor.js the DocBook converter is not included by default, so you need to explicitly require it using `--require`:

```
$ asciidoctor --require @asciidoctor/docbook-converter --backend docbook doc.adoc
```

**Comment by butcherpete** [comment]
Thanks!

**Comment by Mogztter** [comment]
@butcherpete I believe that the documentation could be improved. Feel free to open a pull request to provide additional information on how to enable docinfo, I will gladly merge it :smile:
